{% set name = "mysql" %}
{% set major_minor_version = "8.0" %}
{% set micro_version = "12" %}
{% set sha256 = "99abae6660b53a462cff7c9fefb56d17f52823e9a964831aee1ae5633d9a2982" %}

package:
  name: {{ name|lower }}
  version: {{ major_minor_version }}.{{ micro_version }}

source:
  fn: mysql-boost-{{ major_minor_version }}.{{ micro_version }}.tar.gz
  url: https://dev.mysql.com/get/Downloads/MySQL-{{ major_minor_version }}/mysql-boost-{{ major_minor_version }}.{{ micro_version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - boost =1.67.0
    - gcc >=4.8.3  # [not osx]
    - clangdev  # [osx]
    - perl
  host:
    - libedit 3.1.20170329
    - openssl 1.0.*

  run:
    - libedit >=3.1.20170329
    - openssl 1.0.*

test:
  commands:
    - mysql_config --version
    - my_print_defaults --version
    - mysqld --help --verbose
    - command -v mysql.server

about:
  home: https://www.mysql.com/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Open source relational database management system.'

  description: |
    The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
    and robust SQL (Structured Query Language) database server. MySQL Server
    is intended for mission-critical, heavy-load production systems as well
    as for embedding into mass-deployed software.

extra:
  recipe-maintainers:
    - beckermr
