{% set version = "8.0.23" %}

package:
  name: mysql-suite
  version: {{ version }}

source:
  # url: https://github.com/mysql/mysql-server/archive/7ed30a748964c009d4909cb8b4b22036ebdef239.zip  # bad
  # url: https://github.com/mysql/mysql-server/archive/761dcc9fe746ffea551f372104c9230643f01fb4.zip  # good
  # url: https://github.com/mysql/mysql-server/archive/d9c1874250f3bc342de042611919e3f75b5a19e0.zip  # bad
  # url: https://github.com/mysql/mysql-server/archive/852884d665326d9f3cb0e84322bcfddfe4f914aa.zip  # good
  # url: https://github.com/mysql/mysql-server/archive/45874ad277356fbd5ba3283e5f52516641a93584.zip  # bad
  # url: https://github.com/mysql/mysql-server/archive/e77126da2ebb10a35e4e0e002e6f439c230c1915.zip  # bad
  # url: https://github.com/mysql/mysql-server/archive/0c2029bc1710928e5de358f3100a030a1c7c8a9c.zip  # good
  # url: https://github.com/mysql/mysql-server/archive/726dbf72d3cbbd461cb3aee8fd0f19bc2c76b069.zip  # good
  # url: https://github.com/mysql/mysql-server/archive/d251327088b6f3054fd3c414ca1202eb2b809421.zip  # bad
  # url: https://github.com/mysql/mysql-server/archive/5222a8de93613da5b233036de30d2a8a449654f6.zip  # good
  # url: https://github.com/mysql/mysql-server/archive/09cebad12275c69a6fbab5cd1af87ea7fae1a313.zip  # good
  url: https://github.com/mysql/mysql-server/archive/a038ae423e6c3ae474e764d64e68dcf0ab4ea676.zip
  #url: https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-boost-{{ version }}.tar.gz
  #sha256: 1c7a424303c134758e59607a0b3172e43a21a27ff08e8c88c2439ffd4fc724a5
  patches:
    - patches/0001-Make-installation-of-pdb-files-optional.patch
    - patches/0002-Fix-file-path-for-mysqlrouter.conf.sample-for-instal.patch
    - patches/0003-Allow-flags-other-than-macros-in-CPPFLAGS.patch
    - patches/0004-Add-include-header-for-std-string.patch
    - patches/0005-Use-macports-legacy-support-for-features-10.9.patch
    - patches/0006-Remove-forceful-injection-of-debug-info.patch
    - patches/0007-Link-libgcc-libstdc-statically-for-codgen-binaries.patch
    - patches/0008-Make-LIBEVENT_PTHREADS-conditional-on-CMAKE_USE_PTHR.patch
    - patches/0009-Use-lower-case-for-boolean-type.patch

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - m2-bison  # [win]
  host:
    - cyrus-sasl               # [unix]
    - icu
    - libedit                  # [unix]
    - libevent
    - libprotobuf
    - lz4-c
    - macports-legacy-support  # [osx]
    - openldap                 # [unix]
    - openssl
    - zlib
    - zstd
    - boost-cpp  # [win]


about:
  home: https://www.mysql.com/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open source relational database management system.

  description: |
    The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
    and robust SQL (Structured Query Language) database server. MySQL Server
    is intended for mission-critical, heavy-load production systems as well
    as for embedding into mass-deployed software.


extra:
  recipe-maintainers:
    - beckermr
    - nehaljwani
