{% set name = "mysql" %}
{% set version = "5.7.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.mysql.com/archives/get/p/23/file/mysql-boost-{{ version }}.tar.gz
  md5: 8d271d282fa9033e8bffecced62e653e
  patches:
    - version-file-0000.patch

build:
  number: 0
  skip: true  # [win]
  merge_build_host: True

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - perl

test:
  commands:
    - mysql_config --version
    - my_print_defaults --version
    - mysqld --help --verbose
    - command -v mysql.server

about:
  home: https://www.mysql.com/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Open source relational database management system.'

  description: |
    The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
    and robust SQL (Structured Query Language) database server. MySQL Server
    is intended for mission-critical, heavy-load production systems as well
    as for embedding into mass-deployed software.

extra:
  recipe-maintainers:
    - beckermr
