travis:
  secure:
    BINSTAR_TOKEN: dudBhSEqMTVIe8TXJIMQk1hEaOWshMPRH9lnZSlLCKpZEygsZ+P5+h2D/0L9gAZzV1qSq5o41my9UiDzpV4pW7PgOmuGmoOY66vORiwtp4GbCCDZzHu4UoNQ8UgmdrdD3i0F7gWZ3XLNPCFkTb+hxHjzdg4Smyly19C5TZoXHnPs9t7Qt4a63vkz3tQmFgXk3gYNuDkCi8Yr8OY6TrUcVh53cV+fThZ5O/KvycqsLRX7g04X2mHrYqYruZM09u4j1ES9AUDKeFn0JogyQ91AZRQ35YxcFTd1+JAoHMY/tmqKogzNH1D5j2m6ckqIxR6JYLer09KuuR+ZGfON6ADRIsXOdfxUFWQa8Z7v8SehnIWlVT8x8xPCRFitT0OuWhqtlE+TPXO8Rcvs9WEEiLfu+DeuILNYHuO6klZEaoa+7qEjJehZ7fQ93CMQMfvtZE7tHIVGC1QB2H3Pm8jt006YDuO23w/BQgwR4zuG2DrDr1aFS0qtlqPbvHc6t1fSX0ihnOpAcuJ7iQesHqJymfJYAF7DK4A1TKoPpNfrY8k3MIqNN9tkqJ49WTVP3G1/yIq4Zt5ZQ40H1KFWHsTewtVANz0+4lulGgzJqf+qqtO+XsRpX+RLnjVh5rdd2EJpRAqm16j2dF0V+R77KCHRy58IDBj9LRx3to7lIZa47X1CMxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle
