travis:
  secure:
    BINSTAR_TOKEN: eYOi/rOacht5QQzYIb/YmY6cea9xMj/2bBPLDPXASJQC22xq0EPAL3BP1Aqb7fSLEA1P9u52t8Ms3qKzGgWjCuVNkjbZAgkoFOqPR86RL2JQZ2i1Yg3V3pGFGrLdk3agDZXJs3y05Pu53btF+bf6ONjL/4qjmU1svtcsWi0ukBowcOldLjM/ylYK9iQSKoSspNcoCLhp/8mto3pXoSjmMv6KHXC/5i4tg5YUJanX2b1uc74T3rwZLaE/3vw0del9GFOIi/5d/hOwMRlb9428/7fiitpXShi/b7Ni8KTz/QnLUGPs3yoQHPIc3sOLA2yl9nn1HoXmwL6TVoXVzaByygeN2LgoNWXe521vX7bkpmbhadPNo5cFmB88E5r2ocbW05NSbz1OFpfgb+DAmGvzKNOOdizMMBKokOf9aLEErDwNsj3M9N1g8RZmt7q4mWz1kGBWgaTGDFC1Tc8ovmPi5qQeV7rPs1PSHO1IIelrUNLPyMT5tnw+8oKXWLPjETcaia9bfRW1FwbKgkV3tXc9OZwSQqwnRnBOAFmXA/U424ws9o7izosCqa97sP3Ji7HieUczMhbZMsdG4TaCgllla8BjsmlQhtNBL0YliQzuqZzV7WQtKpkGDJQ/EeAOg/ey6nAaBXQIkjnJguuMn76QhDLBsUKsSASWaL/2Mo/8Z+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle
